Bump MSRV to 1.51 to fix build with latest plist release
A recent release of plist bumped MSRV to 1.51 (see
https://github.com/ebarnard/rust-plist/pull/72 and discussions theirin), so we
need to do that as well to fix this build error in CI:

```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.5/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```