Add Cargo.lock to avoid flaky CI
Avoids errors like:

    error: failed to parse lock file at: /home/runner/work/syntect/syntect/Cargo.lock

    Caused by:
      lock file version 4 requires `-Znext-lockfile-bump`
    test public_api ... FAILED